### ISSUE TITLE
关于你说的MUX模块写得不一样引起的问题

### ISSUE THREAD

**Issue by Aurora-Devhub** [Misaka-N/TJCS-SingleCircleCPU54#2]
MUX模块为何不写成一个多路选择器呢，为何要单独写一个MUX模块

**Comment by Misaka-N** [comment]
你说的是MUL模块嘛？（我看到你问的是MUX但是意思应该是说MUL）。我觉得MUL涉及到高32位和低32位，而且还有有无符号之分，因此把它们集中起来写一个模块实例化出来能够让整个结构看上去更清晰。我说的那个MUL的问题其实和通过多路选择器还是模块实现没有直接关系，而是在“*”运用时候才产生的

**Comment by Misaka-N** [comment]
在我原版的写法中，我是有符号乘法和无符号乘法分开计算，用signed_result和unsigned_result分别进行存储，最后再根据signed_flag（是否是有符号乘法）进行结果输出。这就导致在实例化时候Vivado认为这里需要用两个“\*”IP核（我们在Vivado中直接使用*号其实是调用了主板中的一个乘法IP核），但是咱们使用的赛灵思的板子上只有一个，这就导致了DSP级联错误；而相反地，如果你是先判断signed_flag，将signed_result和unsigned_result合并到一个result中再进行输出，Vivado在实例化时会认为这里只需要一个\*IP核（应该是它内部做了优化），因此就不会产生DSP错误，就可以正常下板

**Comment by Aurora-Devhub** [comment]
You are right. I understand.
